// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MWS.SharePoint.CUIT
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// UploadDoc2 - Use 'UploadDoc2Params' to pass parameters into this method.
        /// </summary>
        public void UploadDoc2()
        {
            #region Variable Declarations
            HtmlHyperlink uINewdocumentHyperlink = this.UIUploadTestDocAllDocuWindow.UIUploadTestDocAllDocuDocument.UINewdocumentHyperlink;
            HtmlDiv uIItemPane = this.UIUploadTestDocAllDocuWindow.UIUploadTestDocAllDocuDocument.UIItemPane;
            HtmlFileInput uIChooseafileFileInput = this.UIUploadTestDocAllDocuWindow.UIUploadTestDocAllDocuDocument.UIDlgFrame336738b094b8Frame.UIAddadocumentDocument.UIChooseafileFileInput;
            HtmlInputButton uIOKButton = this.UIUploadTestDocAllDocuWindow.UIUploadTestDocAllDocuDocument.UIDlgFrame336738b094b8Frame.UIAddadocumentDocument.UIOKButton;
            #endregion

            // Click 'new document' link
            Mouse.Click(uINewdocumentHyperlink, new Point(102, 19));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (322, 194)
            Mouse.Hover(uIItemPane, new Point(322, 194));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Type 'C:\MWS\CUIT\SharePoint\MWS.SharePoint.CUIT\SampleFiles\SampleFile_01.pdf' in 'Choose a file' file input
            uIChooseafileFileInput.FileName = this.UploadDoc2Params.UIChooseafileFileInputFileName;

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(34, 23));
        }
        
        #region Properties
        public virtual UploadDoc2Params UploadDoc2Params
        {
            get
            {
                if ((this.mUploadDoc2Params == null))
                {
                    this.mUploadDoc2Params = new UploadDoc2Params();
                }
                return this.mUploadDoc2Params;
            }
        }
        
        public UIUploadTestDocAllDocuWindow UIUploadTestDocAllDocuWindow
        {
            get
            {
                if ((this.mUIUploadTestDocAllDocuWindow == null))
                {
                    this.mUIUploadTestDocAllDocuWindow = new UIUploadTestDocAllDocuWindow();
                }
                return this.mUIUploadTestDocAllDocuWindow;
            }
        }
        #endregion
        
        #region Fields
        private UploadDoc2Params mUploadDoc2Params;
        
        private UIUploadTestDocAllDocuWindow mUIUploadTestDocAllDocuWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'UploadDoc2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UploadDoc2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'C:\MWS\CUIT\SharePoint\MWS.SharePoint.CUIT\SampleFiles\SampleFile_01.pdf' in 'Choose a file' file input
        /// </summary>
        public string UIChooseafileFileInputFileName = "C:\\MWS\\CUIT\\SharePoint\\MWS.SharePoint.CUIT\\SampleFiles\\SampleFile_01.pdf";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUploadTestDocAllDocuWindow : BrowserWindow
    {
        
        public UIUploadTestDocAllDocuWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "UploadTestDoc - All Documents";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("UploadTestDoc - All Documents");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIUploadTestDocAllDocuDocument UIUploadTestDocAllDocuDocument
        {
            get
            {
                if ((this.mUIUploadTestDocAllDocuDocument == null))
                {
                    this.mUIUploadTestDocAllDocuDocument = new UIUploadTestDocAllDocuDocument(this);
                }
                return this.mUIUploadTestDocAllDocuDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIUploadTestDocAllDocuDocument mUIUploadTestDocAllDocuDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUploadTestDocAllDocuDocument : HtmlDocument
    {
        
        public UIUploadTestDocAllDocuDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "UploadTestDoc - All Documents";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/sites/MWS/_layouts/15/start.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://shpt-app-13a/sites/MWS/_layouts/15/start.aspx#/UploadTestDoc/Forms/AllItem" +
                "s.aspx";
            this.WindowTitles.Add("UploadTestDoc - All Documents");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UINewdocumentHyperlink
        {
            get
            {
                if ((this.mUINewdocumentHyperlink == null))
                {
                    this.mUINewdocumentHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUINewdocumentHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "idHomePageNewDocument-WPQ2";
                    this.mUINewdocumentHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUINewdocumentHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_self";
                    this.mUINewdocumentHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "new document";
                    this.mUINewdocumentHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/sites/MWS/_layouts/15/Upload.aspx";
                    this.mUINewdocumentHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Add a new item to this list or library.";
                    this.mUINewdocumentHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://shpt-app-13a/sites/MWS/_layouts/15/Upload.aspx?List={81BDE442-2032-4171-AD" +
                        "F8-C4DDDAF75921}&RootFolder=";
                    this.mUINewdocumentHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ms-heroCommandLink";
                    this.mUINewdocumentHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=idHomePageNewDocument-WPQ2 class=ms-h";
                    this.mUINewdocumentHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "43";
                    this.mUINewdocumentHyperlink.WindowTitles.Add("UploadTestDoc - All Documents");
                    #endregion
                }
                return this.mUINewdocumentHyperlink;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ms-dlgOverlay";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"Z-INDEX: 1504; WIDTH: 1920px; DISPLAY: block; HEIGHT: 1122px\" class=ms-dlg" +
                        "Overlay";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "114";
                    this.mUIItemPane.WindowTitles.Add("UploadTestDoc - All Documents");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public UIDlgFrame336738b094b8Frame UIDlgFrame336738b094b8Frame
        {
            get
            {
                if ((this.mUIDlgFrame336738b094b8Frame == null))
                {
                    this.mUIDlgFrame336738b094b8Frame = new UIDlgFrame336738b094b8Frame(this);
                }
                return this.mUIDlgFrame336738b094b8Frame;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUINewdocumentHyperlink;
        
        private HtmlDiv mUIItemPane;
        
        private UIDlgFrame336738b094b8Frame mUIDlgFrame336738b094b8Frame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDlgFrame336738b094b8Frame : HtmlIFrame
    {
        
        public UIDlgFrame336738b094b8Frame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "DlgFrame336738b0-94b8-41aa-b163-08ff37248bb5";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/sites/MWS/_layouts/15/Upload.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "http://shpt-app-13a/sites/MWS/_layouts/15/Upload.aspx?List={81BDE442-2032-4171-AD" +
                "F8-C4DDDAF75921}&RootFolder=&IsDlg=1";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = "ms-dlgFrame";
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "style=\"WIDTH: 591px; HEIGHT: 159px\" id=D";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("UploadTestDoc - All Documents");
            #endregion
        }
        
        #region Properties
        public UIAddadocumentDocument UIAddadocumentDocument
        {
            get
            {
                if ((this.mUIAddadocumentDocument == null))
                {
                    this.mUIAddadocumentDocument = new UIAddadocumentDocument(this);
                }
                return this.mUIAddadocumentDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIAddadocumentDocument mUIAddadocumentDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAddadocumentDocument : HtmlDocument
    {
        
        public UIAddadocumentDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Add a document";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/sites/MWS/_layouts/15/Upload.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://shpt-app-13a/sites/MWS/_layouts/15/Upload.aspx?List={81BDE442-2032-4171-AD" +
                "F8-C4DDDAF75921}&RootFolder=&IsDlg=1";
            this.WindowTitles.Add("UploadTestDoc - All Documents");
            #endregion
        }
        
        #region Properties
        public HtmlFileInput UIChooseafileFileInput
        {
            get
            {
                if ((this.mUIChooseafileFileInput == null))
                {
                    this.mUIChooseafileFileInput = new HtmlFileInput(this);
                    #region Search Criteria
                    this.mUIChooseafileFileInput.SearchProperties[HtmlFileInput.PropertyNames.Id] = "ctl00_PlaceHolderMain_UploadDocumentSection_ctl05_InputFile";
                    this.mUIChooseafileFileInput.SearchProperties[HtmlFileInput.PropertyNames.Name] = "ctl00$PlaceHolderMain$UploadDocumentSection$ctl05$InputFile";
                    this.mUIChooseafileFileInput.FilterProperties[HtmlFileInput.PropertyNames.LabeledBy] = null;
                    this.mUIChooseafileFileInput.FilterProperties[HtmlFileInput.PropertyNames.Title] = "Choose a file";
                    this.mUIChooseafileFileInput.FilterProperties[HtmlFileInput.PropertyNames.Class] = "ms-fileinput ms-fullWidth";
                    this.mUIChooseafileFileInput.FilterProperties[HtmlFileInput.PropertyNames.ControlDefinition] = "id=ctl00_PlaceHolderMain_UploadDocumentS";
                    this.mUIChooseafileFileInput.FilterProperties[HtmlFileInput.PropertyNames.TagInstance] = "26";
                    this.mUIChooseafileFileInput.WindowTitles.Add("UploadTestDoc - All Documents");
                    #endregion
                }
                return this.mUIChooseafileFileInput;
            }
        }
        
        public HtmlInputButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_PlaceHolderMain_ctl03_RptControls_btnOK";
                    this.mUIOKButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$PlaceHolderMain$ctl03$RptControls$btnOK";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "OK";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.Class] = "ms-ButtonHeightWidth";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "accessKey=O id=ctl00_PlaceHolderMain_ctl";
                    this.mUIOKButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "28";
                    this.mUIOKButton.WindowTitles.Add("UploadTestDoc - All Documents");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlFileInput mUIChooseafileFileInput;
        
        private HtmlInputButton mUIOKButton;
        #endregion
    }
}
